version: '3'
services:

  manufacturing-factory-facility-manager-service:
    image: quay.io/qiotmanufacturing/factory-facility-manager:1.0.0-beta1
    container_name: "manufacturing-factory-facility-manager-service"
    restart: "no"
    networks:
      - manufacturing-datacenterconnect
      - manufacturing-factory
      - manufacturing-factoryconnect
    expose:
      - "8080"
      - "8443"
    ports:
      - "5100:8080"
      - "5143:8443"
    volumes:
      - facility-shared-storage:/var/data/qiot
    environment:
      QUARKUS_PROFILE: "staging"
#      LOG_LEVEL: "DEBUG"
      QIOT_LOG_LEVEL: "DEBUG"
      ENABLE_SSL: "false"
      INSECURE_HTTP_STATUS: "enabled"
      DB_URL: "manufacturing-factory-sqlstorage:5432"
      FACTORY_SERIAL: "testfactoryserial01"
      FACTORY_NAME: "testfactoryname01"
      CERT_STORE_PASSWORD: "123456"
      PLANT_MANAGER_SERVICE_URL: "http://manufacturing-datacenter-plant-manager-service:8080"
#      PLANT_MANAGER_SERVICE_URL: "https://manufacturing-datacenter-plant-manager-service:8443"
#      DO_RESET: "true"

  manufacturing-factory-productline-service:
    image: quay.io/qiotmanufacturing/factory-product-line:1.0.0-beta1
    container_name: "manufacturing-factory-productline-service"
    restart: "no"
    networks:
      - manufacturing-datacenterconnect
      - manufacturing-factory
      - manufacturing-factoryconnect
    expose:
      - "8080"
    ports:
      - "5101:8080"
    volumes:
      - facility-shared-storage:/var/data/qiot
    environment:
      QUARKUS_PROFILE: "staging"
#      LOG_LEVEL: "DEBUG"
#      QIOT_LOG_LEVEL: "DEBUG"
      ENABLE_SSL: "false"
      INSECURE_HTTP_STATUS: "enabled"
      MONGODB_URL: "mongodb://manufacturing-factory-nosqlstorage:27017"
      MONGODB_DATABASE: "qiot_manufacturing"
      MONGODB_USER: "qiotmanufacturing"
      MONGODB_PASSWORD: "qiotmanufacturingpassword"
      BROKER_URL: "manufacturing-factory-broker:61616"
      KAFKA_BOOTSTRAP_URL: "manufacturing-datacenter-kafka:9092"

  manufacturing-factory-validator-service:
    image: quay.io/qiotmanufacturing/factory-production-validator:1.0.0-beta1
    container_name: "manufacturing-factory-validator-service"
    restart: "no"
    networks:
      - manufacturing-datacenterconnect
      - manufacturing-factory
      - manufacturing-factoryconnect
    volumes:
      - facility-shared-storage:/var/data/qiot
    environment:
      QUARKUS_PROFILE: "staging"
#      LOG_LEVEL: "DEBUG"
      QIOT_LOG_LEVEL: "DEBUG"
      ENABLE_SSL: "false"
      MONGODB_URL: "mongodb://manufacturing-factory-nosqlstorage:27017"
      MONGODB_DATABASE: "qiot_manufacturing"
      MONGODB_USER: "qiotmanufacturing"
      MONGODB_PASSWORD: "qiotmanufacturingpassword"
      BROKER_URL: "manufacturing-factory-broker:61616"
      KAFKA_BOOTSTRAP_URL: "manufacturing-datacenter-kafka:9092"
      FACTORY_PRODUCTLINE_SERVICE_URL: "http://manufacturing-factory-productline-service:8080"
      FACTORY_FACILITY_MANAGER_SERVICE_URL: "http://manufacturing-factory-facility-manager-service:8080"

volumes:
  facility-shared-storage:
networks:
  manufacturing-datacenterconnect:
    external: true
  manufacturing-factory:
    external: true
  manufacturing-factoryconnect:
    external: true
  default:
    external:
      name: manufacturing-factory


