version: '3'
services:

  manufacturing-datacenter-registration-service:
    image: quay.io/qiotmanufacturing/datacenter-registration:1.0.0-beta1
    container_name: "manufacturing-datacenter-registration-service"
    restart: "always"
    networks:
      - manufacturing-datacenter
    expose:
      - "8080"
    ports:
      - "5202:8080"
    environment:
      QUARKUS_PROFILE: "staging"
      QIOT_LOG_LEVEL: "DEBUG"
      CERT_MANAGER_ENABLED: "false"

  manufacturing-datacenter-plant-manager-service:
    image: quay.io/qiotmanufacturing/datacenter-plant-manager:1.0.0-beta1
    container_name: "manufacturing-datacenter-plant-manager-service"
    restart: "no"
    networks:
      - manufacturing-datacenter
      - manufacturing-datacenterconnect
    expose:
      - "8080"
      - "8443"
    ports:
      - "5200:8080"
      - "5243:8443"
    environment:
      QUARKUS_PROFILE: "staging"
#      LOG_LEVEL: "DEBUG"
#      QIOT_LOG_LEVEL: "DEBUG"
      ENABLE_SSL: "false"
      INSECURE_HTTP_STATUS: "enabled"
      DB_URL: "manufacturing-datacenter-sqlstorage:5432"
      REGISTRATION_SERVICE_URL: "http://manufacturing-datacenter-registration-service:8080"

  manufacturing-datacenter-productline-service:
    image: quay.io/qiotmanufacturing/datacenter-product-line:1.0.0-beta1
    container_name: "manufacturing-datacenter-productline-service"
    restart: "no"
    networks:
      - manufacturing-datacenter
      - manufacturing-datacenterconnect
    ports:
      - "5201:8080"
    environment:
      QUARKUS_PROFILE: "staging"
#      LOG_LEVEL: "DEBUG"
#      QIOT_LOG_LEVEL: "DEBUG"
      ENABLE_SSL: "false"
      INSECURE_HTTP_STATUS: "enabled"
      MONGODB_URL: "mongodb://manufacturing-datacenter-nosqlstorage:27017"
      MONGODB_DATABASE: "qiot_manufacturing"
      MONGODB_USER: "qiotmanufacturing"
      MONGODB_PASSWORD: "qiotmanufacturingpassword"
      KAFKA_BOOTSTRAP_URL: "manufacturing-datacenter-kafka:9092"

  manufacturing-datacenter-eventcollector-service:
    image: quay.io/qiotmanufacturing/datacenter-event-collector-jvm:1.0.0-beta1
    container_name: "manufacturing-datacenter-eventcollector-service"
    restart: "no"
    networks:
      - manufacturing-datacenter
    environment:
      QUARKUS_PROFILE: "staging"
#      LOG_LEVEL: "DEBUG"
#      QIOT_LOG_LEVEL: "DEBUG"
      ENABLE_SSL: "false"
      INSECURE_HTTP_STATUS: "enabled"
      KAFKA_BOOTSTRAP_URL: "manufacturing-datacenter-kafka:9092"
      INFLUXDB_CONNECTION_URL: "http://manufacturing-datacenter-influxdb:8086"
      INFLUXDB_ORG_ID: "qiot"
      INFLUXDB_DATA_BUCKET_ID: "manufacturing"
      INFLUXDB_TOKEN: "qiotmanufacturinginfluxdbtoken"

networks:
  manufacturing-datacenter:
    external: true
  manufacturing-datacenterconnect:
    external: true
  default:
    external:
      name: manufacturing-datacenter


